### ISSUE TITLE
Error while actions

### ISSUE THREAD

**Issue by wurikiji** [subosito/flutter-action#10]
![image](https://user-images.githubusercontent.com/5652744/66251512-b50ea780-e705-11e9-83a7-5981f2ecf087.png)

I got errors like above. Could you give me some hints to debug it? 
I just copied and pasted your example scripts. 

# workflows

```yaml
name: Flutter Test and Build

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'master'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
```

**Comment by mackattack3k** [comment]
I hade the same problem and I think it comes from only specifying `channel: master`. This causes [version.replace](https://github.com/subosito/flutter-action/blob/8f119fb49d2a1bc58737c18b4943e7bbcf1b0d84/lib/installer.js#L52) to fail.

It seems as if the `master` version isn't available in `releases_OS.json` and therefore not supported

**Comment by wurikiji** [comment]
@mackattack3k Thanks for oyour information. I will try beta and comment a result here.

**Comment by subosito** [comment]
@wurikiji as @mackattack3k said, `master` is not a valid name for channel. As you can see on https://flutter.dev/docs/development/tools/sdk/releases?tab=linux, the valid channel names are: `stable`, `beta` and `dev`.

**Comment by wurikiji** [comment]
Thank you so much all of you @mackattack3k @subosito. It is solved with other channel names.

**Comment by KLD** [comment]
I'll just leave this here so it appears in search: 

##[error]Cannot read property 'replace' of undefined

**Comment by liudonghua123** [comment]
I have the same issue, I want to build desktop app, so the master channel is a must, I read the doc, and I think maybe the dev channel is close to master channel. But desktop features is still not available in dev channel.

![image](https://user-images.githubusercontent.com/2276718/76216441-916b0280-624b-11ea-8968-fe7f16373799.png)

**Comment by liudonghua123** [comment]
I can change to master channel in the following command.

```yml
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev" # optional, default to: 'stable'
      - run: flutter channel master
      - run: flutter upgrade
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
```

**Comment by wurikiji** [comment]
@liudonghua123 Thanks! This is simple and great solution.
